# Generated by Django 3.1.2 on 2021-03-30 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='customer', serialize=False, to='auth.user')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('addressLine1', models.CharField(max_length=50)),
                ('addressLine2', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('pincode', models.CharField(max_length=8, null=True)),
                ('phone1', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('phone2', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('email', models.CharField(max_length=50)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driverID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('phone1', models.IntegerField()),
                ('hiringDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('vehicle_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('category', models.CharField(max_length=32)),
                ('subcategory', models.CharField(default='None', max_length=32)),
                ('description', models.CharField(max_length=200)),
                ('stock', models.IntegerField()),
                ('individual_price', models.FloatField()),
                ('bulk_price', models.FloatField()),
                ('req_team_size', models.IntegerField()),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('datePublised', models.DateTimeField(null=True)),
                ('webStatus', models.BooleanField(default=False)),
                ('image', models.FileField(null=True, upload_to='products/')),
                ('paymentMode', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplierID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('GSTINNum', models.CharField(max_length=20)),
                ('companyname', models.CharField(max_length=20)),
                ('addressLine1', models.CharField(max_length=50)),
                ('addressLine2', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('pincode', models.CharField(max_length=8, null=True)),
                ('phone1', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('phone2', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('profileImg', models.FileField(null=True, upload_to='supplier/')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('walletID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('balance', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionID', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.FloatField()),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('walletID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HAVE_eCommerce.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('team_size', models.IntegerField(default=1)),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HAVE_eCommerce.product')),
            ],
        ),
        migrations.CreateModel(
            name='Sells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HAVE_eCommerce.product')),
                ('supplierID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HAVE_eCommerce.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('cost', models.FloatField()),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('orderType', models.CharField(max_length=20)),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HAVE_eCommerce.product')),
                ('teamID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='HAVE_eCommerce.team')),
                ('transactionID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HAVE_eCommerce.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MetaKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metaKeyword', models.CharField(max_length=20)),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HAVE_eCommerce.product')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('date_of_departure', models.DateTimeField()),
                ('date_of_arrival', models.DateTimeField()),
                ('delivery_status', models.CharField(max_length=10)),
                ('driverID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='HAVE_eCommerce.driver')),
                ('transactionID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HAVE_eCommerce.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='BelongsTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HAVE_eCommerce.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
