# Generated by Django 3.1.2 on 2021-03-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HAVE_eCommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='walletID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
